# version: '3.9'
version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rails:
    build:
      context: ./rails
    command: bundle exec rails server -e production -b 0.0.0.0 -p ${PORT:-3000}
    volumes:
      - ./rails:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgresql://myportfolio_db_5zxi_user:USsfa3NtL2oIy3Tu8sXtwaHFG5PwDeOD@dpg-d1brtgodl3ps73evun80-a.singapore-postgres.render.com/myportfolio_db_5zxi
      CORS_ORIGINS: https://my-portfolio-five-lovat-o9u46t7cag.vercel.app

  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
      - /app/node_modules
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=https://myportfolio-tdl6.onrender.com

volumes:
  postgres_data:
