# version: '3.9'
services:
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  next:
      build:
        context: ./next
        dockerfile: Dockerfile
      tty: true
      stdin_open: true
      volumes:
        - ./next:/app
      ports:
        - "8000:3000"
      environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
volumes:
  mysql_data: