#RenderへデプロイするためPostgreSQL用に編集

development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: 5432

