# テスト(rspec)、コードルール(rubocop, eslint, prettier)のチェックを行う
name: Continuous Integration

# 当 workflow の実行タイミング
# ブランチへの push 時
on:
  push:

# 当 workflow が行う処理
jobs:
  # 処理① rspec がオールグリーンであることをチェック
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@127.0.0.1:5432/myapp_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7
          bundler: 2.6.3
          bundler-cache: true

      - name: Bundler install
        run: bundle install --jobs 4 --retry 3

      - name: Prepare database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run RSpec
        run: bundle exec rspec


  # 処理② rubocop のルール違反がないことをチェック
  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7
          bundler: 2.6.3
          bundler-cache: true  # Bundlerのキャッシュを有効化

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Verify RuboCop installation
        run: bundle exec rubocop -v

      - name: Run RuboCop
        run: bundle exec rubocop


  # 処理③ eslint(& prettier) のルール違反がないことをチェック
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install

      - name: Run lint
        run: npm run lint